### ISSUE TITLE
Is BlueBottle still under development?

### ISSUE THREAD

**Issue by perpi** [onepercentclub/bluebottle#1777]
Hi there

We're going to run a crowdfunding website. There are not many options out there, but there are some apps as in: Bluebottle, Goteo (php), Catarse (ruby), openTilt (ruby), Thrinica (SAAS).

Anyway, Bluebottle is one of them that we see have not been under heavy development for years. Would you work on it again?

Do you recommend it as base of our website?

**Comment by gannetson** [comment]
Hi @perpi, 

Bluebottle is under heavy develop ment ;-) Our develop branch almost daily updates.
However Bluebottle is just the API part of our SaaS platform. To run a website you need a front end too. We use Reef for that. That repository is currently not open source. We plan to open it up in the next few weeks. 

As of yet I couldn't recommend our repo as a base of your own product. It's still too much geared to our specific use. We are planning to open it up so it could be of use to other software developers, but I don't think that'll happen in the next few months.
Cheers,
Loek
